site_name: 稳定性架构：分布式系统的设计与实践
site_url: https://github.com/ahan-ai/stability
site_description: 使用 MkDocs 编写和发布的电子书
site_author: 阿涵
theme:
  name: material
  language: zh

plugins:
  - with-pdf:
      output_path: site/stability.pdf
      author: "阿涵"
      copyright: "© 2025"
      toc_level: 2            # 目录展开到 H2
      verbose: true
      toc_title: 目录
      enabled_if_env: ENABLE_PDF_EXPORT
      stylesheets:
        - css/pdf.css

nav:
  - 第一部分 稳定性架构设计:
      - 如何衡量稳定性: 1-overview/README.md
      - 避免单点故障: 2-preventive-arch/避免单点故障.md
      - 备份核心数据: 2-preventive-arch/备份.md
      - 隔离: 2-preventive-arch/隔离.md
      - 删除保护: 2-preventive-arch/删除保护.md
      - 兼容性设计: 2-preventive-arch/兼容性设计.md
      - 灰度: 2-preventive-arch/灰度.md
      - 无感升级: 2-preventive-arch/无感升级.md
      - 流量控制: 2-preventive-arch/流量控制.md
      - 重试: 2-preventive-arch/重试.md
      - 容灾切换: 2-preventive-arch/容灾切换.md
      - SOP: 2-preventive-arch/SOP.md
      - 应急指挥: 2-preventive-arch/应急指挥.md

  - 第二部分 可观测性:
      - 第1章: 3-observability/README.md
      - 可观测架构: 3-observability/可观测架构.md
      - 指标监控: 3-observability/指标监控.md
      - 告警: 3-observability/告警.md
  
  - 第三部分 测试与演练:
      - 测试: 4-test/测试.md
      - 测试流水线: 4-test/测试流水线.md
      - 单元测试: 4-test/单元测试.md
      - 故障注入: 4-test/故障注入.md
      - golang_test: 4-test/golang_test.md
# extra_css:
#   - stylesheets/extra.css  # 如果网页样式和 PDF 样式不同，可分开