site_name: 我的电子书
site_url: https://github.com/ahan-ai/stability
site_description: 使用 MkDocs 编写和发布的电子书
site_author: 阿涵
theme:
  name: material

plugins:
  - with-pdf:
      output_path: site/mybook.pdf
      pdf_stylesheets:
        - docs/pdf.css
nav:
  - 简介: index.md
extra_css:
  - stylesheets/extra.css  # 如果网页样式和 PDF 样式不同，可分开