site_name: 我的电子书
site_url: https://github.com/ahan-ai/stability
site_description: 使用 MkDocs 编写和发布的电子书
site_author: 阿涵
theme:
  name: material

plugins:
  - search
  - with-pdf:
      output_path: site/mybook.pdf    # 生成 PDF 文件位置
      media_type: print               # 打印样式
      toc: true                       # 包含目录
      pdf_stylesheets:
        - docs/pdf.css                # PDF 专用样式
nav:
  - 简介: index.md
extra_css:
  - stylesheets/extra.css  # 如果网页样式和 PDF 样式不同，可分开