name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-with-pdf

      - name: Build site and PDF
        run: mkdocs build --clean

      - name: Debug check site directory
        run: ls -lh site

      - name: Create release and upload PDF
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: "自动生成的电子书 PDF"
          files: site/mybook.pdf   # 如果 ls 结果里没有这个文件，需要改这里
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
